### ISSUE TITLE
Running your accessing_data_example notebook  error

### ISSUE THREAD

**Issue by chiaral** [carbonplan/cmip6-downscaling#260]
I am trying to run your [accessing_data_example.ipynb ](https://github.com/carbonplan/cmip6-downscaling/blob/main/notebooks/accessing_data_example.ipynb) and I am running it on the [ml-notebook pangeo docker](https://github.com/pangeo-data/pangeo-docker-images) image. 

I first install the missing packages:
```
!pip install carbonplan_data
!pip install watermark
!python -m pip install "carbonplan-styles"
!pip install git+https://github.com/carbonplan/cmip6-downscaling.git
```

and when I run the second cell

```
from cmip6_downscaling.analysis.analysis import (
    qaqc_checks,
    grab_big_city_data,
    load_big_cities,
    get_seasonal,
    change_ds,
)
from cmip6_downscaling.analysis.plot import plot_city_data
from cmip6_downscaling.analysis.analysis import change_ds

xr.set_options(keep_attrs=True)
```
I get:

```ModuleNotFoundError: No module named 'cmip6_downscaling.analysis'```

in fact, if I try tab complete that module does not appear. Am I doing something wrong? 
thanks!

**Comment by maxrjones** [comment]
👋 @chiaral, thanks for reaching out about the data access example notebook! Could you try using `%pip` rather than `!pip`, which will install the packages into the currently running kernel? You may need to restart the kernel after using the [pip magic command](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-pip).

**Comment by chiaral** [comment]
oh! that was a silly thing! the other packages loaded correctly so I didn't think about that. Thanks! it fixed the issue and things seem to be working fine!
