### ISSUE TITLE
CMIP6 downscaling

### ISSUE THREAD

**Issue by Abebemengistu** [carbonplan/cmip6-downscaling#320]

**Comment by Abebemengistu** [comment]
Dear, I am new to GitHub and I don't know how to use it and how to work on the codes! my main problem is to downscale CMIP6 climate data using statistical methods. I want your help in this regard.

**Comment by norlandrhagen** [comment]
Hi there @Abebemengistu. Our cmip6 downscaling data is available through an intake catalog. You can find details in the [Data Access section of the README.md](https://github.com/carbonplan/cmip6-downscaling#data-access). There is also a [jupyter-notebook ](https://github.com/carbonplan/cmip6-downscaling/blob/main/notebooks/accessing_data_example.ipynb)demonstrating how to use the data.

Alternatively, NASA has a free to access downscaled CMIP6 dataset available on the [AWS public data access portal.](https://registry.opendata.aws/nasanex/).

Hopefully this is helpful!
