### ISSUE TITLE
Generating multiscale pyramids for raw CMIP6 data

### ISSUE THREAD

**Issue by jhamman** [carbonplan/cmip6-downscaling#42]
### Background

We're interested in generating a decent sized collection of CMIP6 data, reprojected into web-mercator for use in `@carbonplan/maps`. This issue is meant to track the initial prototypes for that process.

### Initial approach

The following code sample generates multiscale data pyramids for raw CMIP6 data. 

```python
import intake

import rioxarray
from ndpyramid import  pyramid_reproject


# open cmip6 data catalog
col_url = "https://cmip6downscaling.blob.core.windows.net/cmip6/pangeo-cmip6.json"
cat = intake.open_esm_datastore(col_url).search(member_id=['r1i1p1f1'], table_id=["day"], grid_label=['gn'])

# get a dataset
for key, entry in cat.items():
    print(key)
    ds = entry(storage_options={'account_name': 'cmip6downscaling'}).to_dask()
    ds = ds.squeeze('member_id', drop=True)
    ds = ds.rio.write_crs('EPSG:4326')
    break  # remove when its time to loop over the full collection

# generate the pyramid
pyramid = pyramid_reproject(ds, levels=2)
pyramid.to_zarr(...)
```

Warning, I suspect that this will not be particularly performant and that we may want to use a different method for doing the reproduction. 

Passing this off to you @freeman-lab. cc @katamartin

**Comment by jhamman** [comment]
See also: https://github.com/carbonplan/ndpyramid/issues/10

**Comment by andersy005** [comment]
this has been implemented via `ndypramid's pyramid_regrid()` functionality.
